# Generated by Django 3.0.3 on 2020-07-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0003_journalentry_journalentrylineitem'),
        ('tasks', '0002_tasklog_expense_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='journal_entry',
            field=models.ForeignKey(help_text='Reference to journal_entry', null=True, on_delete=django.db.models.deletion.PROTECT, to='netsuite.JournalEntry'),
        ),
    ]
