# Generated by Django 3.0.3 on 2021-05-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0011_creditcardcharge_creditcardchargelineitem'),
        ('tasks', '0004_auto_20201221_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='credit_card_charge',
            field=models.ForeignKey(help_text='Reference to CC Charge', null=True, on_delete=django.db.models.deletion.PROTECT, to='netsuite.CreditCardCharge'),
        ),
    ]
