# Generated by Django 3.1.13 on 2021-12-06 08:56

import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210715_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='detail',
            field=models.JSONField(default=apps.tasks.models.get_default, help_text='Task response', null=True),
        ),
    ]
