# Generated by Django 3.1.14 on 2022-03-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20211206_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='type',
            field=models.CharField(choices=[('CREATING_JOURNAL_ENTRY', 'CREATING_JOURNAL_ENTRY'), ('CREATING_EXPENSE_REPORT', 'CREATING_EXPENSE_REPORT'), ('CREATING_BILL', 'CREATING_BILL'), ('CREATING_VENDOR_PAYMENT', 'CREATING_VENDOR_PAYMENT'), ('FETCHING_EXPENSES', 'FETCHING_EXPENSES'), ('CREATING_CREDIT_CARD_CHARGE', 'CREATING_CREDIT_CARD_CHARGE'), ('CREATING_CREDIT_CARD_REFUND', 'CREATING_CREDIT_CARD_REFUND')], help_text='Task type (FETCH_EXPENSES / CREATE_BILL)', max_length=50),
        ),
    ]
