# Generated by Django 3.2.14 on 2024-04-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='article_link',
            field=models.CharField(blank=True, help_text='Error Help Article Link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error',
            name='is_parsed',
            field=models.BooleanField(default=False, help_text='is the error parsed'),
        ),
    ]
