# Generated by Django 3.2.14 on 2024-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20240422_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='article_link',
            field=models.CharField(blank=True, help_text='Error Help Article Link', max_length=255, null=True),
        ),
    ]
