# Generated by Django 4.2.20 on 2025-03-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_tasklog_expense_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='triggered_by',
            field=models.CharField(choices=[('WEBHOOK', 'WEBHOOK'), ('DASHBOARD_SYNC', 'DASHBOARD_SYNC'), ('DIRECT_EXPORT', 'DIRECT_EXPORT'), ('BACKGROUND_SCHEDULE', 'BACKGROUND_SCHEDULE')], help_text='Triggered by', max_length=255, null=True),
        ),
    ]
