# Generated by Django 4.2.22 on 2025-08-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_error_mapping_error_expense_group_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='re_attempt_export',
            field=models.BooleanField(default=False, help_text='Is re-attempt export'),
        ),
    ]
