# Generated by Django 4.2.27 on 2026-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_tasklog_re_attempt_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='is_attachment_upload_failed',
            field=models.BooleanField(default=False, help_text='Is Attachment Upload Failed'),
        ),
    ]
