FYLE_EXPENSE_SYSTEM_FIELDS = [
    'employee id',
    'organisation name',
    'employee name',
    'employee email',
    'expense date',
    'expense id',
    'report id',
    'employee id',
    'department',
    'state',
    'reporter',
    'report',
    'purpose',
    'vendor',
    'category',
    'category code',
    'mileage distance',
    'mileage unit',
    'flight from city',
    'flight to city',
    'flight from date',
    'flight to date',
    'flight from class',
    'flight to class',
    'hotel checkin',
    'hotel checkout',
    'hotel location',
    'hotel breakfast',
    'currency',
    'amount',
    'foreign currency',
    'foreign amount',
    'tax',
    'approver',
    'project',
    'billable',
    'cost center',
    'cost center code',
    'approved on',
    'reimbursable',
    'receipts',
    'paid date',
    'expense created date'
]

DEFAULT_NETSUITE_IMPORT_TYPES = [
    'LOCATION',
    'PROJECT',
    'TAX_ITEM',
    'VENDOR',
    'EMPLOYEE'
]

SYNC_METHODS = {
    'ACCOUNT': 'accounts',
    'EXPENSE_CATEGORY': 'expense_categories',
    'ITEM': 'items',
    'TAX_ITEM': 'tax_items',
    'CUSTOMER': 'customers',
    'VENDOR': 'vendors',
    'PROJECT': 'projects',
    'DEPARTMENT': 'departments',
    'LOCATION': 'locations',
    'CLASS': 'classifications',
    'custom_segments': 'custom_segments',
}
