# Generated by Django 3.0.3 on 2020-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='fund_source',
            field=models.CharField(default='DEFAULT', help_text='Expense fund source', max_length=255),
            preserve_default=False,
        ),
    ]
