# Generated by Django 3.0.3 on 2020-09-29 12:42

import apps.fyle.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspacegeneralsettings_workspaceschedule_workspacesettings'),
        ('fyle', '0002_expensegroup_fund_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='custom_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='verified_at',
            field=models.DateTimeField(help_text='Report verified at', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='settlement_id',
            field=models.CharField(help_text='Settlement ID', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseGroupSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reimbursable_expense_group_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.fyle.models.get_default_expense_group_fields, help_text='list of fields reimbursable expense grouped by', size=None)),
                ('corporate_credit_card_expense_group_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.fyle.models.get_default_expense_group_fields, help_text='list of fields ccc expenses grouped by', size=None)),
                ('expense_state', models.CharField(default=apps.fyle.models.get_default_expense_state, help_text='state at which the expenses are fetched ( PAYMENT_PENDING / PAYMENT_PROCESSING / PAID)', max_length=100)),
                ('export_date_type', models.CharField(default='current_date', help_text='Export Date', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.OneToOneField(help_text='To which workspace this expense group setting belongs to', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
        ),
    ]
