# Generated by Django 3.0.3 on 2020-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0006_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_on_netsuite',
            field=models.BooleanField(default=False, help_text='Expense Payment status on NetSuite'),
        ),
    ]
