# Generated by Django 3.0.3 on 2020-12-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0007_expense_paid_on_netsuite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expensegroupsettings',
            table='expense_group_settings',
        ),
    ]
