# Generated by Django 3.0.3 on 2021-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0008_auto_20201228_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='billable',
            field=models.BooleanField(help_text='Expense Billable or not', null=True),
        ),
    ]
