# Generated by Django 3.0.3 on 2021-08-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0010_expense_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroupsettings',
            name='import_card_credits',
            field=models.BooleanField(default=False, help_text='Import Card Credits'),
        ),
    ]
