# Generated by Django 3.0.3 on 2021-09-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0011_expensegroupsettings_import_card_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroupsettings',
            name='export_date_type',
        ),
        migrations.AddField(
            model_name='expensegroupsettings',
            name='ccc_export_date_type',
            field=models.CharField(default='current_date', help_text='CCC Export Date', max_length=100),
        ),
        migrations.AddField(
            model_name='expensegroupsettings',
            name='reimbursable_export_date_type',
            field=models.CharField(default='current_date', help_text='Reimbursable Export Date', max_length=100),
        ),
    ]
