# Generated by Django 3.0.3 on 2021-11-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0013_auto_20210924_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensegroupsettings',
            old_name='export_date_type',
            new_name='reimbursable_export_date_type',
        ),
        migrations.AddField(
            model_name='expensegroupsettings',
            name='ccc_export_date_type',
            field=models.CharField(default='current_date', help_text='CCC Export Date', max_length=100),
        ),
    ]
