# Generated by Django 3.1.14 on 2022-01-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0015_auto_20211206_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='project_id',
            field=models.CharField(blank=True, help_text='Project ID', max_length=255, null=True),
        ),
    ]
