# Generated by Django 3.1.14 on 2022-01-07 10:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0015_auto_20211206_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='exported',
        ),
        migrations.AddField(
            model_name='expense',
            name='file_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='File IDs', null=True, size=None),
        ),
    ]
