# Generated by Django 3.1.14 on 2022-12-01 11:47

import apps.fyle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0019_expensegroupsettings_ccc_expense_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='ccc_expense_state',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PAID', 'PAID'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING')], default=apps.fyle.models.get_default_ccc_expense_state, help_text='state at which the ccc expenses are fetched (APPROVED/PAID)', max_length=100, null=True),
        ),
    ]
