# Generated by Django 3.1.14 on 2023-01-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0021_auto_20221222_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee_name',
            field=models.CharField(help_text='Name of the Fyle employee', max_length=255, null=True),
        ),
    ]
