# Generated by Django 3.1.14 on 2022-12-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0029_auto_20221202_0620'),
        ('fyle', '0021_auto_20221222_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensefilter',
            name='workspace',
            field=models.ForeignKey(help_text='To which workspace these filters belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='expense_filters', to='workspaces.workspace'),
        ),
    ]
