# Generated by Django 3.1.14 on 2023-06-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0024_auto_20230116_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='posted_at',
            field=models.DateTimeField(help_text='Date when the money is taken from the bank', null=True),
        ),
        migrations.AlterField(
            model_name='expensefilter',
            name='operator',
            field=models.CharField(choices=[('isnull', 'isnull'), ('in', 'in'), ('iexact', 'iexact'), ('icontains', 'icontains'), ('lt', 'lt'), ('lte', 'lte'), ('not_in', 'not_in')], help_text='Operator for the filter', max_length=255),
        ),
    ]
