# Generated by Django 3.1.14 on 2023-10-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0035_auto_20231019_1025'),
        ('fyle', '0025_auto_20230622_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupsettings',
            name='workspace',
            field=models.OneToOneField(help_text='To which workspace this expense group setting belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='expense_group_settings', to='workspaces.workspace'),
        ),
    ]
