# Generated by Django 3.1.14 on 2023-11-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0026_auto_20231025_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='employee_name',
            field=models.CharField(help_text='Expense Group Employee Name', max_length=100, null=True),
        ),
    ]
