# Generated by Django 3.1.14 on 2023-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0027_expensegroup_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='export_url',
            field=models.CharField(help_text='Netsuite URL for the exported expenses', max_length=255, null=True),
        ),
    ]
