# Generated by Django 3.1.14 on 2023-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0028_expensegroup_export_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='employee_name',
            field=models.CharField(help_text='Expense Group Employee Name', max_length=255, null=True),
        ),
    ]
