# Generated by Django 3.1.14 on 2024-02-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0038_configuration_allow_intercompany_vendors'),
        ('fyle', '0029_auto_20231130_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='accounting_export_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='expense',
            name='previous_export_state',
            field=models.CharField(help_text='Previous export state', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='workspace',
            field=models.ForeignKey(help_text='To which workspace this expense belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
    ]
