# Generated by Django 3.2.14 on 2024-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0032_alter_expensefilter_custom_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_on_fyle',
            field=models.BooleanField(default=False, help_text='Expense Payment status on Fyle'),
        ),
    ]
