# Generated by Django 4.2.20 on 2025-03-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0037_auto_20241226_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='imported_from',
            field=models.CharField(choices=[('WEBHOOK', 'WEBHOOK'), ('DASHBOARD_SYNC', 'DASHBOARD_SYNC'), ('DIRECT_EXPORT', 'DIRECT_EXPORT'), ('BACKGROUND_SCHEDULE', 'BACKGROUND_SCHEDULE')], help_text='Imported from source', max_length=255, null=True),
        ),
    ]
