# Generated by Django 4.2.26 on 2025-11-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0040_alter_expense_imported_from'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['workspace_id', 'report_id'], name='expenses_workspa_ad984e_idx'),
        ),
    ]
