# Generated by Django
from django.db import migrations
from apps.internal.helpers import safe_run_sql
sql_files = [
    'fyle-integrations-db-migrations/netsuite/functions/delete_workspace.sql',
    'fyle-integrations-db-migrations/netsuite/functions/re_export_expenses_netsuite.sql'
]
class Migration(migrations.Migration):
    dependencies = [('internal', '0006_auto_generated_sql')]
    operations = safe_run_sql(sql_files)
