# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('netsuite', '0028_netsuiteattributescount'),('internal', '0011_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO netsuite_attributes_count (workspace_id, created_at, updated_at)
                SELECT id, now(), now()
                FROM workspaces
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM netsuite_attributes_count
                    WHERE workspace_id = workspaces.id
                );
            """,
            reverse_sql="""
                DELETE FROM netsuite_attributes_count
                WHERE EXISTS (
                    SELECT 1
                    FROM netsuite_attributes_count
                    WHERE workspace_id = netsuite_attributes_count.workspace_id
                );
            """
        )
    ]
