# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('netsuite', '0028_netsuiteattributescount'),('internal', '0011_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO netsuite_attributes_count (workspace_id, accounts_count, expense_categories_count, items_count, currencies_count, locations_count, classifications_count, departments_count, vendors_count, employees_count, tax_items_count, projects_count, customers_count, created_at, updated_at)
                SELECT id, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, now(), now()
                FROM workspaces
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM netsuite_attributes_count
                    WHERE workspace_id = workspaces.id
                );
            """,
            reverse_sql="""
                DELETE FROM netsuite_attributes_count
                WHERE EXISTS (
                    SELECT 1
                    FROM netsuite_attributes_count
                    WHERE workspace_id = netsuite_attributes_count.workspace_id
                );
            """
        )
    ]
