# Generated by Django 3.0.3 on 2020-06-03 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(help_text='Fyle project', max_length=255)),
                ('department_name', models.CharField(help_text='NetSuite department name', max_length=255)),
                ('department_id', models.CharField(help_text='NetSuite department id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'unique_together': {('project', 'workspace')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_email', models.CharField(help_text='Fyle employee email', max_length=255)),
                ('vendor_name', models.CharField(help_text='NetSuite vendor name', max_length=255)),
                ('vendor_id', models.CharField(help_text='NetSuite vendor id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'unique_together': {('employee_email', 'workspace')},
            },
        ),
        migrations.CreateModel(
            name='CostCenterMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_center', models.CharField(help_text='Fyle cost center', max_length=255)),
                ('location_name', models.CharField(help_text='NetSuite location name', max_length=255)),
                ('location_id', models.CharField(help_text='NetSuite location id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'unique_together': {('cost_center', 'workspace')},
            },
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='Fyle category', max_length=255)),
                ('sub_category', models.CharField(help_text='Fyle sub category', max_length=255)),
                ('account_name', models.CharField(help_text='NetSuite account name', max_length=255)),
                ('account_id', models.CharField(help_text='NetSuite account id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'unique_together': {('category', 'sub_category', 'workspace')},
            },
        ),
    ]
