# Generated by Django 3.0.3 on 2020-06-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(help_text='NetSuite Location name', max_length=255)),
                ('internal_id', models.CharField(help_text='NetSuite Location id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'db_table': 'location_mappings',
                'unique_together': {('location_name', 'workspace')},
            },
        ),
    ]
