# Generated by Django 3.0.3 on 2020-09-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0002_auto_20200718_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='default_ccc_vendor_id',
            field=models.CharField(help_text='Default CCC Vendor ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='default_ccc_vendor_name',
            field=models.CharField(help_text='Default CCC Vendor Name', max_length=255, null=True),
        ),
    ]
