# Generated by Django 3.0.3 on 2020-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0002_auto_20200718_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmapping',
            name='accounts_payable_id',
            field=models.CharField(help_text='NetSuite Accounts Payable Account id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalmapping',
            name='accounts_payable_name',
            field=models.CharField(help_text='NetSuite Accounts Payable Account name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalmapping',
            name='default_ccc_account_id',
            field=models.CharField(help_text='CCC Expenses Account id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalmapping',
            name='default_ccc_account_name',
            field=models.CharField(help_text='CCC Expenses Account name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalmapping',
            name='reimbursable_account_id',
            field=models.CharField(help_text='Reimbursable Expenses Account id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalmapping',
            name='reimbursable_account_name',
            field=models.CharField(help_text='Reimbursable Expenses Account name', max_length=255, null=True),
        ),
    ]
