# Generated by Django 3.0.3 on 2020-11-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0003_auto_20200917_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='vendor_payment_account_id',
            field=models.CharField(help_text='NetSuite VendorPayment Account id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='vendor_payment_account_name',
            field=models.CharField(help_text='VendorPayment Account name', max_length=255, null=True),
        ),
    ]
