# Generated by Django 3.0.3 on 2020-09-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0003_auto_20200917_1134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generalmapping',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='generalmapping',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='generalmapping',
            name='location_name',
        ),
    ]
