# Generated by Django 3.0.3 on 2021-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0005_generalmapping_location_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='department_level',
            field=models.CharField(help_text='Transaction Body, Line, Both', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='use_employee_department',
            field=models.BooleanField(default=False, help_text='use employee department in netsuite'),
        ),
    ]
