# Generated by Django 3.0.3 on 2021-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0006_auto_20210306_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='department_id',
            field=models.CharField(help_text='Netsuite Department id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='department_name',
            field=models.CharField(help_text='Netsuite Department Name', max_length=255, null=True),
        ),
    ]
