# Generated by Django 3.0.3 on 2021-07-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_auto_20210609_1331'),
        ('mappings', '0006_auto_20210306_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmapping',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace'),
        ),
        migrations.AlterField(
            model_name='subsidiarymapping',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='generalmapping',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subsidiarymapping',
            unique_together=set(),
        ),
    ]
