# Generated by Django 3.0.3 on 2021-09-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0007_auto_20210714_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiarymapping',
            name='country_name',
            field=models.CharField(help_text='Netsuite Subsidiary Country', max_length=255, null=True),
        ),
    ]
