# Generated by Django 3.0.3 on 2021-10-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0008_subsidiarymapping_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='use_employee_class',
            field=models.BooleanField(default=False, help_text='use employee class in netsuite'),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='use_employee_location',
            field=models.BooleanField(default=False, help_text='use employee location in netsuite'),
        ),
    ]
