# Generated by Django 3.1.14 on 2024-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0011_auto_20231107_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='override_tax_details',
            field=models.BooleanField(default=False, help_text='Override tax details'),
        ),
    ]
