# Generated by Django 3.2.14 on 2024-11-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0014_auto_20240417_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='is_tax_balancing_enabled',
            field=models.BooleanField(default=False, help_text='Is tax balancing enabled'),
        ),
    ]
