# Generated by Django 3.2.14 on 2025-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0016_auto_20241226_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmapping',
            name='is_tax_balancing_enabled',
            field=models.BooleanField(default=True, help_text='Is tax balancing enabled'),
        ),
    ]
