# Generated by Django 3.0.3 on 2020-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='location_id',
            field=models.CharField(help_text='NetSuite Location id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='location_id',
            field=models.CharField(help_text='NetSuite location id', max_length=255, null=True),
        ),
    ]
