# Generated by Django 3.0.3 on 2020-06-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='class_id',
            field=models.CharField(help_text='NetSuite Class id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='department_id',
            field=models.CharField(help_text='NetSuite department id', max_length=255, null=True),
        ),
    ]
