# Generated by Django 3.0.3 on 2020-09-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0003_auto_20200924_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='transaction_date',
            field=models.DateField(help_text='Expense Report transaction date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='transaction_date',
            field=models.DateField(help_text='Journal Entry transaction date'),
        ),
    ]
