# Generated by Django 3.0.3 on 2020-10-27 09:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspacegeneralsettings_workspaceschedule_workspacesettings'),
        ('netsuite', '0004_expensereportlineitem_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='netsuite_custom_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='NetSuite Custom Segments', null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='netsuite_custom_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='NetSuite Custom Segments', null=True),
        ),
        migrations.AddField(
            model_name='journalentrylineitem',
            name='netsuite_custom_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='NetSuite Custom Segments', null=True),
        ),
        migrations.CreateModel(
            name='CustomSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='NetSuite Record Name', max_length=255)),
                ('segment_type', models.CharField(help_text='NetSuite Custom Type', max_length=255)),
                ('script_id', models.CharField(help_text='NetSuite Transaction Custom Field script id', max_length=255)),
                ('internal_id', models.CharField(help_text='NetSuite Custom Record / Field internal id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'db_table': 'custom_segments',
            },
        ),
    ]
