# Generated by Django 3.0.3 on 2020-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0006_auto_20201207_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_on_netsuite',
            field=models.BooleanField(default=False, help_text='Payment Status in NetSuite'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='paid_on_netsuite',
            field=models.BooleanField(default=False, help_text='Payment Status in NetSuite'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='paid_on_netsuite',
            field=models.BooleanField(default=False, help_text='Payment Status in NetSuite'),
        ),
    ]
