# Generated by Django 3.0.3 on 2021-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0007_auto_20201210_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='billable',
            field=models.BooleanField(help_text='Expense Billable or not', null=True),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='customer_id',
            field=models.CharField(help_text='NetSuite customer id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='billable',
            field=models.BooleanField(help_text='Expense Billable or not', null=True),
        ),
    ]
