# Generated by Django 3.0.3 on 2021-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0008_auto_20210106_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='department_id',
            field=models.CharField(help_text='NetSuite Department id', max_length=255, null=True),
        ),
    ]
