# Generated by Django 3.0.3 on 2021-03-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0009_journalentry_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='memo',
            field=models.TextField(help_text='Journal Entry Memo'),
        ),
    ]
