# Generated by Django 3.0.3 on 2021-05-13 06:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0010_expense_org_id'),
        ('netsuite', '0010_auto_20210308_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_card_account_id', models.CharField(help_text='NetSuite Accounts Payable Account id', max_length=255)),
                ('entity_id', models.CharField(help_text='NetSuite vendor id', max_length=255)),
                ('subsidiary_id', models.CharField(help_text='NetSuite subsidiary id', max_length=255)),
                ('location_id', models.CharField(help_text='NetSuite Location id', max_length=255, null=True)),
                ('currency', models.CharField(help_text='CC Charge Currency', max_length=255)),
                ('memo', models.TextField(help_text='CC Charge Description')),
                ('external_id', models.CharField(help_text='Fyle reimbursement id', max_length=255, unique=True)),
                ('transaction_date', models.DateTimeField(help_text='CC Charge transaction date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('expense_group', models.OneToOneField(help_text='Expense group reference', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup')),
            ],
            options={
                'db_table': 'credit_card_charges',
            },
        ),
        migrations.CreateModel(
            name='CreditCardChargeLineItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(help_text='NetSuite account id', max_length=255)),
                ('location_id', models.CharField(help_text='NetSuite location id', max_length=255, null=True)),
                ('department_id', models.CharField(help_text='NetSuite department id', max_length=255, null=True)),
                ('class_id', models.CharField(help_text='NetSuite Class id', max_length=255, null=True)),
                ('customer_id', models.CharField(help_text='NetSuite customer id', max_length=255, null=True)),
                ('amount', models.FloatField(help_text='CC Charge line amount')),
                ('billable', models.BooleanField(help_text='Expense Billable or not', null=True)),
                ('memo', models.TextField(help_text='NetSuite cc charge lineitem memo', null=True)),
                ('netsuite_custom_segments', django.contrib.postgres.fields.jsonb.JSONField(help_text='NetSuite Custom Segments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('credit_card_charge', models.ForeignKey(help_text='Reference to credit card charge', on_delete=django.db.models.deletion.PROTECT, to='netsuite.CreditCardCharge')),
                ('expense', models.OneToOneField(help_text='Reference to Expense', on_delete=django.db.models.deletion.PROTECT, to='fyle.Expense')),
            ],
            options={
                'db_table': 'credit_card_charge_lineitems',
            },
        ),
    ]
