# Generated by Django 3.0.3 on 2021-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0011_creditcardcharge_creditcardchargelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='credit_card_account_id',
            field=models.CharField(help_text='NetSuite Credit Card Account id', max_length=255, null=True),
        ),
    ]
