# Generated by Django 3.0.3 on 2021-06-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_auto_20210609_1331'),
        ('netsuite', '0012_expensereport_credit_card_account_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customsegment',
            unique_together={('script_id', 'internal_id', 'workspace')},
        ),
    ]
