# Generated by Django 3.0.3 on 2021-07-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0013_auto_20210615_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsegment',
            name='segment_type',
            field=models.CharField(choices=[('CUSTOM_RECORD', 'CUSTOM_RECORD'), ('CUSTOM_LIST', 'CUSTOM_LIST')], help_text='NetSuite Custom Type', max_length=255),
        ),
    ]
