# Generated by Django 3.0.3 on 2021-09-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0014_auto_20210712_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='entity_id',
        ),
    ]
