# Generated by Django 3.0.3 on 2021-09-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0015_remove_journalentry_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='tax_amount',
            field=models.FloatField(help_text='Tax amount', null=True),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='tax_item_id',
            field=models.CharField(help_text='Tax Item ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditcardchargelineitem',
            name='tax_amount',
            field=models.FloatField(help_text='Tax amount', null=True),
        ),
        migrations.AddField(
            model_name='creditcardchargelineitem',
            name='tax_item_id',
            field=models.CharField(help_text='Tax Item ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='tax_amount',
            field=models.FloatField(help_text='Tax amount', null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='tax_item_id',
            field=models.CharField(help_text='Tax Item ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalentrylineitem',
            name='tax_amount',
            field=models.FloatField(help_text='Tax amount', null=True),
        ),
        migrations.AddField(
            model_name='journalentrylineitem',
            name='tax_item_id',
            field=models.CharField(help_text='Tax Item ID', max_length=255, null=True),
        ),
    ]
