# Generated by Django 3.1.13 on 2021-12-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0016_auto_20210924_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billlineitem',
            name='netsuite_custom_segments',
            field=models.JSONField(help_text='NetSuite Custom Segments', null=True),
        ),
        migrations.AlterField(
            model_name='creditcardchargelineitem',
            name='netsuite_custom_segments',
            field=models.JSONField(help_text='NetSuite Custom Segments', null=True),
        ),
        migrations.AlterField(
            model_name='expensereportlineitem',
            name='netsuite_custom_segments',
            field=models.JSONField(help_text='NetSuite Custom Segments', null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylineitem',
            name='netsuite_custom_segments',
            field=models.JSONField(help_text='NetSuite Custom Segments', null=True),
        ),
    ]
