# Generated by Django 3.1.14 on 2022-03-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0017_auto_20211206_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsegment',
            name='segment_type',
            field=models.CharField(choices=[('CUSTOM_RECORD', 'CUSTOM_RECORD'), ('CUSTOM_LIST', 'CUSTOM_LIST'), ('CUSTOM_SEGMENT', 'CUSTOM_SEGMENT')], help_text='NetSuite Custom Type', max_length=255),
        ),
    ]
