# Generated by Django 3.1.14 on 2023-07-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0021_auto_20230523_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardcharge',
            name='department_id',
            field=models.CharField(help_text='NetSuite department id', max_length=255, null=True),
        ),
    ]
