# Generated by Django 3.1.14 on 2023-11-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0022_creditcardcharge_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='department_id',
            field=models.CharField(help_text='NetSuite department id', max_length=255, null=True),
        ),
    ]
