# Generated by Django 3.1.14 on 2024-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0023_bill_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='override_tax_details',
            field=models.BooleanField(default=False, help_text='Override Tax Details'),
        ),
    ]
