# Generated by Django 3.2.14 on 2024-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0026_auto_20240902_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_attachment_upload_failed',
            field=models.BooleanField(default=False, help_text='Is Attachment Upload Failed'),
        ),
        migrations.AddField(
            model_name='creditcardcharge',
            name='is_attachment_upload_failed',
            field=models.BooleanField(default=False, help_text='Is Attachment Upload Failed'),
        ),
        migrations.AddField(
            model_name='creditcardchargelineitem',
            name='netsuite_receipt_url',
            field=models.TextField(help_text='NetSuite Receipt URL', null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='is_attachment_upload_failed',
            field=models.BooleanField(default=False, help_text='Is Attachment Upload Failed'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_attachment_upload_failed',
            field=models.BooleanField(default=False, help_text='Is Attachment Upload Failed'),
        ),
    ]
