# Generated by Django 4.2.26 on 2025-11-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0051_alter_featureconfig_fyle_webhook_sync_enabled'),
        ('netsuite', '0027_auto_20240924_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetSuiteAttributesCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accounts_count', models.IntegerField(default=0, help_text='Number of accounts in NetSuite')),
                ('expense_categories_count', models.IntegerField(default=0, help_text='Number of expense categories in NetSuite')),
                ('items_count', models.IntegerField(default=0, help_text='Number of items in NetSuite')),
                ('currencies_count', models.IntegerField(default=0, help_text='Number of currencies in NetSuite')),
                ('locations_count', models.IntegerField(default=0, help_text='Number of locations in NetSuite')),
                ('classifications_count', models.IntegerField(default=0, help_text='Number of classifications in NetSuite')),
                ('departments_count', models.IntegerField(default=0, help_text='Number of departments in NetSuite')),
                ('vendors_count', models.IntegerField(default=0, help_text='Number of vendors in NetSuite')),
                ('employees_count', models.IntegerField(default=0, help_text='Number of employees in NetSuite')),
                ('tax_items_count', models.IntegerField(default=0, help_text='Number of tax items in NetSuite')),
                ('projects_count', models.IntegerField(default=0, help_text='Number of projects in NetSuite')),
                ('customers_count', models.IntegerField(default=0, help_text='Number of customers in NetSuite')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Updated at datetime')),
                ('workspace', models.OneToOneField(help_text='Reference to workspace', on_delete=django.db.models.deletion.PROTECT, related_name='netsuite_attributes_count', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'netsuite_attributes_count',
            },
        ),
    ]
