# Generated by Django 4.2.27 on 2026-01-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsuite', '0028_netsuiteattributescount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='is_attachment_upload_failed',
        ),
        migrations.RemoveField(
            model_name='creditcardcharge',
            name='is_attachment_upload_failed',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='is_attachment_upload_failed',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='is_attachment_upload_failed',
        ),
    ]
