data = {
    "vendor": [
        {
            "nullFieldList": None,
            "customForm": None,
            "entityId": "Uber BV",
            "altName": None,
            "isPerson": False,
            "phoneticName": None,
            "salutation": None,
            "firstName": None,
            "middleName": None,
            "lastName": None,
            "companyName": "Uber BV",
            "phone": None,
            "fax": None,
            "email": None,
            "url": None,
            "defaultAddress": None,
            "isInactive": False,
            "category": None,
            "title": None,
            "printOnCheckAs": None,
            "altPhone": None,
            "homePhone": None,
            "mobilePhone": None,
            "altEmail": None,
            "comments": None,
            "globalSubscriptionStatus": None,
            "image": None,
            "emailPreference": None,
            "subsidiary": {
                "name": "HoneComb Aus",
                "internalId": "5",
                "externalId": None,
                "type": None,
            },
            "representingSubsidiary": None,
            "accountNumber": None,
            "legalName": "Uber BV",
            "vatRegNumber": None,
            "expenseAccount": None,
            "payablesAccount": None,
            "terms": None,
            "incoterm": None,
            "creditLimit": None,
            "balancePrimary": None,
            "openingBalance": None,
            "openingBalanceDate": None,
            "openingBalanceAccount": None,
            "balance": None,
            "unbilledOrdersPrimary": None,
            "bcn": None,
            "unbilledOrders": None,
            "currency": {
                "name": "USA",
                "internalId": "1",
                "externalId": None,
                "type": None,
            },
            "is1099Eligible": False,
            "isJobResourceVend": False,
            "laborCost": None,
            "purchaseOrderQuantity": None,
            "purchaseOrderAmount": None,
            "purchaseOrderQuantityDiff": None,
            "receiptQuantity": None,
            "receiptAmount": None,
            "receiptQuantityDiff": None,
            "workCalendar": {
                "name": "Default Work Calendar",
                "internalId": "1",
                "externalId": None,
                "type": None,
            },
            "taxIdNum": None,
            "taxItem": None,
            "giveAccess": False,
            "sendEmail": None,
            "billPay": False,
            "isAccountant": None,
            "password": None,
            "password2": None,
            "requirePwdChange": None,
            "eligibleForCommission": None,
            "emailTransactions": None,
            "printTransactions": None,
            "faxTransactions": None,
            "defaultTaxReg": None,
            "pricingScheduleList": None,
            "subscriptionsList": None,
            "addressbookList": None,
            "currencyList": None,
            "rolesList": None,
            "taxRegistrationList": None,
            "customFieldList": {
                "customField": [
                    {
                        "value": False,
                        "internalId": "3992",
                        "scriptId": "custentity_2663_payment_method",
                    },
                    {
                        "value": False,
                        "internalId": "35",
                        "scriptId": "custentity_is_manufacturer",
                    },
                ]
            },
            "internalId": "12106",
            "externalId": "Uber BV",
        }
    ],
    "bill_payload": [
        {
            "nullFieldList": None,
            "createdDate": None,
            "lastModifiedDate": None,
            "nexus": None,
            "subsidiaryTaxRegNum": None,
            "taxRegOverride": None,
            "taxDetailsOverride": None,
            "customForm": None,
            "billAddressList": None,
            "account": {
                "name": None,
                "internalId": "25",
                "externalId": None,
                "type": "account",
            },
            "entity": {
                "name": None,
                "internalId": "10693",
                "externalId": None,
                "type": "vendor",
            },
            "subsidiary": {
                "name": None,
                "internalId": "1",
                "externalId": None,
                "type": "subsidiary",
            },
            "location": {
                "name": None,
                "internalId": "2",
                "externalId": None,
                "type": "location",
            },
            "approvalStatus": None,
            "nextApprover": None,
            "vatRegNum": None,
            "postingPeriod": None,
            "tranDate": "2021-11-11T17:33:24",
            "currencyName": None,
            "billingAddress": None,
            "exchangeRate": None,
            "entityTaxRegNum": None,
            "taxPointDate": None,
            "terms": None,
            "dueDate": None,
            "discountDate": None,
            "tranId": None,
            "userTotal": None,
            "discountAmount": None,
            "taxTotal": None,
            "paymentHold": None,
            "memo": "Reimbursable expenses by admin1@fylefornt.com",
            "tax2Total": None,
            "creditLimit": None,
            "availableVendorCredit": None,
            "currency": {
                "name": None,
                "internalId": "1",
                "externalId": None,
                "type": "currency",
            },
            "status": None,
            "landedCostMethod": None,
            "landedCostPerLine": None,
            "transactionNumber": None,
            "expenseList": [
                {
                    "orderDoc": None,
                    "orderLine": None,
                    "line": None,
                    "category": None,
                    "account": {
                        "name": None,
                        "internalId": "65",
                        "externalId": None,
                        "type": "account",
                    },
                    "amount": 99.0,
                    "memo": "Expense by admin1@fylefornt.com against category Food spent on 2021-11-08 with claim number - C/2021/11/R/2",
                    "grossAmt": 99.0,
                    "taxDetailsReference": None,
                    "department": {
                        "name": None,
                        "internalId": None,
                        "externalId": None,
                        "type": "department",
                    },
                    "class": {
                        "name": None,
                        "internalId": None,
                        "externalId": None,
                        "type": "classification",
                    },
                    "location": {
                        "name": None,
                        "internalId": "2",
                        "externalId": None,
                        "type": "location",
                    },
                    "customer": {
                        "name": None,
                        "internalId": None,
                        "externalId": None,
                        "type": "customer",
                    },
                    "customFieldList": [
                        {
                            "scriptId": "custcolfyle_expense_url",
                            "type": "String",
                            "value": "https://staging.fyle.tech/app/main/#/enterprise/view_expense/txiRmGpGNHyT?org_id=orf6t6jWUnpx",
                        }
                    ],
                    "isBillable": None,
                    "projectTask": None,
                    "tax1Amt": None,
                    "taxAmount": None,
                    "taxCode": {
                        "name": None,
                        "internalId": None,
                        "externalId": None,
                        "type": "classification",
                    },
                    "taxRate1": None,
                    "taxRate2": None,
                    "amortizationSched": None,
                    "amortizStartDate": None,
                    "amortizationEndDate": None,
                    "amortizationResidual": None,
                }
            ],
            "accountingBookDetailList": None,
            "itemList": None,
            "landedCostsList": None,
            "purchaseOrderList": None,
            "taxDetailsList": None,
            "customFieldList": None,
            "internalId": None,
            "externalId": "bill 1258 - admin1@fylefornt.com",
        }
    ],
    "bill_response": [
        ["name", None],
        ["internalId", "115043"],
        ["externalId", "bill 1405 - admin1@fylefornt.com"],
        ["type", "vendorBill"],
    ],
}
