data = {
    "expenses": [
        {
            'id': 'tx4ziVSAyIsv',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/3',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/2',
            'amount': 150,
            'tax_amount': 0,
            'tax_group_id': 'tgWdIdEwcKlK',
            'settled_at': '2021-12-23T07:16:17.034079+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'seteYqkAfuWOS',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpqaDywYdbbw',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-23T07:14:13.990650+00:00',
            'expense_updated_at': '2021-12-27T05:26:43.954470+00:00',
            'source_account_type': 'PERSONAL_CASH_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                  'Vehicle Type': '',
                  'Fyle Categories': '',
            },
        },
        {
            'id': 'tx6wOnBVaumk',
            'employee_email': 'jhonsnow@fyle.in',
            'category': 'Accounts Payable',
            'sub_category': 'Accounts Payable',
            'project': 'Aaron Abbott',
            'project_id': 263589,
            'expense_number': 'E/2021/12/T/2',
            'org_id': 'orsO0VW86WLQ',
            'claim_number': 'C/2021/12/R/1',
            'amount': 99,
            'tax_amount': 16.5,
            'tax_group_id': 'tg3fCYQxjBeC',
            'settled_at': '2021-12-22T07:31:12.857977+00:00',
            'currency': 'USD',
            'foreign_amount': None,
            'foreign_currency': None,
            'settlement_id': 'set5PSfKaloaC',
            'reimbursable': True,
            'billable': False,
            'state': 'PAID',
            'vendor': None,
            'cost_center': None,
            'corporate_card_id': None,
            'purpose': None,
            'report_id': 'rpvpLIPrP1EO',
            'file_ids': [],
            'spent_at': '2021-12-22T07:30:26.289842+00:00',
            'approved_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_created_at': '2021-12-22T07:30:26.289842+00:00',
            'expense_updated_at': '2021-12-23T07:11:39.770191+00:00',
            'source_account_type': 'PERSONAL_CASH_ACCOUNT',
            'verified_at': None,
            'custom_properties': {
                'Vehicle Type': '',
                'Fyle Categories': '',
            },
        },
    ],
    "expense_group_expenses": [
        {
            "id": 150,
            "employee_email": "admin1@fylefornt.com",
            "category": "Food",
            "sub_category": "Food",
            "project": "Project 9",
            "org_id": "orf6t6jWUnpx",
            "expense_id": "txiRmGpGNHyT",
            "expense_number": "E/2021/11/T/6",
            "claim_number": "C/2021/11/R/2",
            "amount": 99.0,
            "currency": "USD",
            "foreign_amount": None,
            "foreign_currency": None,
            "tax_amount": None,   # Todo : cleanup and fix the keys later
            "tax_group_id": None,
            "settlement_id": "setZp4pb4VhBu",
            "reimbursable": True,
            "billable": None,
            "exported": False,
            "state": "PAYMENT_PROCESSING",
            "vendor": None,
            "cost_center": "SME",
            "purpose": None,
            "report_id": "rpErQpeH8G9b",
            "spent_at": "2021-11-08T00:00:00Z",
            "approved_at": "2021-11-08T00:00:00Z",
            "expense_created_at": "2021-11-08T06:23:35.631000Z",
            "expense_updated_at": "2021-11-08T06:24:09.562000Z",
            "created_at": "2021-11-10T21:24:30.524010Z",
            "updated_at": "2021-11-10T21:24:30.524015Z",
            "source_account_type": "PERSONAL_CASH_ACCOUNT",
            "verified_at": None,
            "paid_on_netsuite": False,
            "custom_properties": {},
        }
    ],
    "expense_group_id": {
        "id": 1,
        "fund_source": "PERSONAL",
        "description": {
            "report_id": "rpuN3bgphxbK",
            "fund_source": "PERSONAL",
            "claim_number": "C/2021/11/R/5",
            "employee_email": "ashwin.t@fyle.in",
        },
        "response_logs": {
            "name": None,
            "type": "expenseReport",
            "externalId": "03294720937402397402937",
            "internalId": "116142",
        },
        "created_at": "2021-11-15T10:29:07.618062Z",
        "exported_at": "2021-11-15T11:02:55.125205Z",
        "updated_at": "2021-11-15T11:02:55.125634Z",
        "workspace": 1,
        "expenses": [1],
    },
    "expense_group_setting_response": {
        "id": 1,
        "reimbursable_expense_group_fields": [
            "employee_email",
            "report_id",
            "claim_number",
            "fund_source"
        ],
        "corporate_credit_card_expense_group_fields": [
            "employee_email",
            "report_id",
            "claim_number",
            "fund_source"
        ],
        "expense_state": "PAYMENT_PROCESSING",
        "reimbursable_export_date_type": "current_date",
        "ccc_export_date_type": "current_date",
        "import_card_credits": "false",
        "created_at": "2021-11-15T08:46:16.069944Z",
        "updated_at": "2021-11-15T08:46:16.069986Z",
        "workspace": 1
    },
    "fyle_orgs": [
        {
            "id": "orf6t6jWUnpx",
            "created_at": "2021-06-21T12:02:32.463Z",
            "updated_at": "2021-06-21T12:02:46.618Z",
            "name": "Fyle For NetSuite Testing",
            "domain": "fylefornt.com",
            "currency": "USD",
            "branch_ifsc": None,
            "branch_account": None,
            "tally_bank_ledger": None,
            "tally_default_category": None,
            "tally_default_user": None,
            "corporate_credit_card_details": {
                "bank_name": None,
                "number_of_cards": None,
            },
            "verified": True,
            "lite": False,
            "dwolla_customers_metadata_id": "dcmFudU7eReqs",
        }
    ],
    'expense_attributes':
    [{
        'id': 3235,
        'attribute_type': 'FYLE_CATEGORY',
        'display_name': 'Fyle Category',
        'value': 'Category 1',
        'source_id': 'expense_custom_field.fyle category.1',
        'auto_mapped': False,
        'auto_created': False,
        'active': None,
        'detail': {'custom_field_id': 104346},
        'created_at': '2021-11-16T04:17:43.787712Z',
        'updated_at': '2021-11-16T04:17:43.787737Z',
        'workspace': 2,
    }, {
        'id': 3236,
        'attribute_type': 'FYLE_CATEGORY',
        'display_name': 'Fyle Category',
        'value': 'Category 2',
        'source_id': 'expense_custom_field.fyle category.2',
        'auto_mapped': False,
        'auto_created': False,
        'active': None,
        'detail': {'custom_field_id': 104346},
        'created_at': '2021-11-16T04:17:43.787784Z',
        'updated_at': '2021-11-16T04:17:43.787793Z',
        'workspace': 2,
    }, {
        'id': 3237,
        'attribute_type': 'FYLE_CATEGORY',
        'display_name': 'Fyle Category',
        'value': 'Category 3',
        'source_id': 'expense_custom_field.fyle category.3',
        'auto_mapped': False,
        'auto_created': False,
        'active': None,
        'detail': {'custom_field_id': 104346},
        'created_at': '2021-11-16T04:17:43.787828Z',
        'updated_at': '2021-11-16T04:17:43.787836Z',
        'workspace': 2,
    }, {
        'id': 3238,
        'attribute_type': 'FYLE_CATEGORY',
        'display_name': 'Fyle Category',
        'value': 'Category 4',
        'source_id': 'expense_custom_field.fyle category.4',
        'auto_mapped': False,
        'auto_created': False,
        'active': None,
        'detail': {'custom_field_id': 104346},
        'created_at': '2021-11-16T04:17:43.787870Z',
        'updated_at': '2021-11-16T04:17:43.787878Z',
        'workspace': 2,
    }],
    'reimbursements': [
        {
            'amount': 76,
            'code': None,
            'created_at': '2022-01-20T16:30:44.584100',
            'creator_user_id': 'usqywo0f3nBY',
            'currency': 'USD',
            'id': 'reimgCW1Og0BcM',
            'is_exported': False,
            'is_paid': False,
            'mode': 'OFFLINE',
            'org_id': 'orsO0VW86WLQ',
            'paid_at': None,
            'purpose': 'C/2022/01/R/2;Ashwin',
            'reimbursement_number': 'P/2022/01/R/2',
            'settlement_id': 'setgCxsr2vTmZ',
            'updated_at': '2022-01-20T16:30:44.584100',
            'user_id': 'usqywo0f3nBY',
        }
    ],
    'expense_group_setting_payload': {
        'reimbursable_expense_group_fields': ['claim_number'],
        'corporate_credit_card_expense_group_fields': ['claim_number'],
        'expense_state': 'PAYMENT_PROCESSING',
        'reimbursable_export_date_type': 'current_date',
        'ccc_export_date_type': 'current_date',
    }
}
