# Generated by Django 3.0.3 on 2020-11-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0009_auto_20171009_0915'),
        ('workspaces', '0002_workspacegeneralsettings_workspaceschedule_workspacesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceschedule',
            name='fyle_job_id',
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_q.Schedule'),
        ),
    ]
