# Generated by Django 3.0.3 on 2020-11-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20201109_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='sync_fyle_to_netsuite_payments',
            field=models.BooleanField(default=False, help_text='Auto Sync Payments from Fyle to Netsuite'),
        ),
    ]
