# Generated by Django 3.0.3 on 2020-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20201109_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='import_projects',
            field=models.BooleanField(default=False, help_text='Auto import projects to Fyle'),
        ),
    ]
