# Generated by Django 3.0.3 on 2020-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_workspacegeneralsettings_sync_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='sync_netsuite_to_fyle_payments',
            field=models.BooleanField(default=False, help_text='Auto Sync Payments from NetSuite to Fyle'),
        ),
    ]
