# Generated by Django 3.0.3 on 2021-01-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_auto_20201228_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='import_projects',
            field=models.BooleanField(default=False, help_text='Auto import projects to Fyle'),
        ),
    ]
