# Generated by Django 3.0.3 on 2021-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspacegeneralsettings_auto_map_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='import_categories',
            field=models.BooleanField(default=False, help_text='Auto import categories to Fyle'),
        ),
    ]
