# Generated by Django 3.0.3 on 2021-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_workspacegeneralsettings_auto_create_merchants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='corporate_credit_card_expenses_object',
            field=models.CharField(choices=[('EXPENSE REPORT', 'EXPENSE REPORT'), ('JOURNAL ENTRY', 'JOURNAL ENTRY'), ('BILL', 'BILL'), ('CREDIT CARD CHARGE', 'CREDIT CARD CHARGE')], help_text='Corporate Card Expenses type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='reimbursable_expenses_object',
            field=models.CharField(choices=[('EXPENSE REPORT', 'EXPENSE REPORT'), ('JOURNAL ENTRY', 'JOURNAL ENTRY'), ('BILL', 'BILL')], help_text='Reimbursable Expenses type', max_length=50),
        ),
    ]
