# Generated by Django 3.0.3 on 2021-06-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_auto_20210609_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacegeneralsettings',
            name='auto_map_employees',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('NAME', 'NAME'), ('EMPLOYEE_CODE', 'EMPLOYEE_CODE')], help_text='Auto Map Employees type from NetSuite to Fyle', max_length=50, null=True),
        ),
    ]
