# Generated by Django 3.0.3 on 2021-06-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_auto_20210609_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkspaceGeneralSettings',
            new_name='Configuration',
        ),
        migrations.AlterModelTable(
            name='configuration',
            table='configurations',
        ),
    ]
