# Generated by Django 3.0.3 on 2021-08-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_auto_20210609_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='employee_field_mapping',
            field=models.CharField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('VENDOR', 'VENDOR')], help_text='Employee field mapping', max_length=50, null=True),
        ),
    ]
