# Generated by Django 3.0.3 on 2021-08-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_auto_20210609_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='import_tax_items',
            field=models.BooleanField(default=False, help_text='Auto import tax items to Fyle'),
        ),
    ]
