# Generated by Django 3.1.13 on 2021-12-24 07:51

import apps.workspaces.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_configuration_change_accounting_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='memo_structure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.workspaces.models.get_default_memo_fields, help_text='list of system fields for creating custom memo', size=None),
        ),
    ]
