# Generated by Django 3.1.14 on 2022-02-08 13:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0021_fylecredential_cluster_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceschedule',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Admin Email', null=True, size=None),
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='errors',
            field=models.IntegerField(null=True),
        ),
    ]
