# Generated by Django 3.1.14 on 2022-02-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0021_fylecredential_cluster_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='map_fyle_cards_netsuite_account',
            field=models.BooleanField(default=True, help_text='Map Fyle Cards to Netsuite Account'),
        ),
    ]
