# Generated by Django 3.1.14 on 2022-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0022_configuration_map_fyle_cards_netsuite_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='skip_cards_mapping',
            field=models.BooleanField(default=False, help_text='Skip cards mapping'),
        ),
    ]
