# Generated by Django 3.1.14 on 2022-02-28 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0023_configuration_skip_cards_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceschedule',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Admin Email', null=True, size=None),
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='total_errors',
            field=models.IntegerField(help_text='Number of errors in export', null=True),
        ),
    ]
