# Generated by Django 3.1.14 on 2022-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0024_auto_20220310_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='import_vendors_as_merchants',
            field=models.BooleanField(default=False, help_text='Auto import vendors from netsuite as merchants to Fyle'),
        ),
    ]
