# Generated by Django 3.1.14 on 2022-11-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0025_configuration_import_vendors_as_merchants'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='import_netsuite_employees',
            field=models.BooleanField(default=False, help_text='Auto import employees from netsuite as employees to Fyle'),
        ),
    ]
