# Generated by Django 3.1.14 on 2022-11-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0026_configuration_import_netsuite_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='employee_exported_at',
            field=models.DateTimeField(auto_now=True, help_text='Employee exported to Fyle at datetime'),
        ),
    ]
