# Generated by Django 3.1.14 on 2022-12-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0026_workspace_ccc_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_simplify_report_closure_enabled',
            field=models.BooleanField(default=False, help_text='Simplify report closure is enbaled'),
        ),
    ]
