# Generated by Django 3.1.14 on 2022-11-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0027_workspace_employee_exported_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='employee_exported_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Employee exported to Fyle at datetime'),
        ),
    ]
