# Generated by Django 3.1.14 on 2023-03-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0029_auto_20221202_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='is_simplify_report_closure_enabled',
            field=models.BooleanField(default=True, help_text='Simplify report closure is enbaled'),
        ),
    ]
