# Generated by Django 3.1.14 on 2023-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0030_auto_20230321_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='import_items',
            field=models.BooleanField(default=False, help_text='Auto import Items to Fyle'),
        ),
    ]
