# Generated by Django 3.1.14 on 2023-11-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0036_lastexportdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastexportdetail',
            name='next_export',
            field=models.DateTimeField(help_text='next export datetime', null=True),
        ),
    ]
