# Generated by Django 3.2.14 on 2024-10-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0038_configuration_allow_intercompany_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='je_single_credit_line',
            field=models.BooleanField(default=False, help_text='Journal Entry Single Credit Line'),
        ),
    ]
