# Generated by Django 3.2.14 on 2024-11-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0039_configuration_je_single_credit_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='change_accounting_period',
            field=models.BooleanField(default=True, help_text='Change the accounting period'),
        ),
    ]
