# Generated by Django 3.2.14 on 2024-12-19 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0041_configuration_is_attachment_upload_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at datetime', null=True),
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated at datetime', null=True),
        ),
        migrations.AddField(
            model_name='workspaceuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, help_text='Created at datetime'),
        ),
        migrations.AddField(
            model_name='workspaceuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, help_text='Updated at datetime'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='user',
            field=models.ManyToManyField(help_text='Reference to users table', through='workspaces.WorkspaceUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
