# Generated by Django 4.2.20 on 2025-04-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0043_auto_20241224_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='is_simplify_report_closure_enabled',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='skip_cards_mapping',
        ),
    ]
