# Generated by Django 4.2.20 on 2025-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0044_remove_configuration_is_simplify_report_closure_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsuitecredentials',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Marks if credentials are expired'),
        ),
    ]
