# Generated by Django 4.2.20 on 2025-04-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0045_configuration_skip_accounting_export_summary_post'),
        ('workspaces', '0045_netsuitecredentials_is_expired'),
    ]

    operations = [
    ]
