# Generated by Django 4.2.21 on 2025-05-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0045_configuration_skip_accounting_export_summary_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceschedule',
            name='is_real_time_export_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
