# Generated by Django 4.2.20 on 2025-04-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0045_configuration_skip_accounting_export_summary_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsuitecredentials',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Marks if credentials are expired'),
        ),
    ]
