# Generated by Django 4.2.21 on 2025-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0046_workspaceschedule_is_real_time_export_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='import_classes_with_parent',
            field=models.BooleanField(default=False, help_text='Import classes with parent'),
        ),
    ]
