# Generated by Django 4.2.22 on 2025-07-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0047_configuration_import_classes_with_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsuitecredentials',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Marks if credentials are expired'),
        ),
    ]
