# Generated by Django 4.2.22 on 2025-07-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0048_netsuitecredentials_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastexportdetail',
            name='unmapped_card_count',
            field=models.IntegerField(default=0, help_text='count of unmapped card'),
        ),
    ]
