# Generated by Django 4.2.28 on 2026-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0052_workspace_org_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='skip_posting_gross_amount',
            field=models.BooleanField(default=False, help_text='Skip posting gross amount'),
        ),
    ]
